### ISSUE TITLE
Getting francetv videos with subtitles

### ISSUE THREAD

**Issue by ahjun001** [simulot/aspiratv#32]
Not an issue, but a desirable development, particularly for non-French speakers

Subtitles in French being available on the francetv site while viewing videos, It would be great if these subtitles could be selected to be included when videos are downloaded with aspiratv.

Thanks

**Comment by simulot** [comment]
Great suggestion, thank you.

I'll check how to do that for channels that provide subtitles and multiple sound track.

**Comment by rockandska** [comment]
Hi,

Thanks for aspiratv, seems really nice.

Even for French speakers who love to watch in VO, it will be great to have the possibility to choose the language for audio/subtitles.

Regards,

**Comment by simulot** [comment]
Hi

> Thanks for aspiratv, seems really nice.

Thanks you! 

> Even for French speakers who love to watch in VO, it will be great to have the possibility to choose the language for audio/subtitles.
> 
> Regards,

Hi,
Subtitles are send in its own stream in DASH stream, and are not forced on the video stream. Alas FFMEG  can't handle the stream. Depending on the version, FFMPEG just ignores it otherwise stops before downloading anything. 

I have tested with ffmpeg v3.4 coming with ubuntu and the latest available 4.2. 

More problematic, the audio stream labelled "VO" is in French even for English shows like Brokenwood. English isn't available on webplayer too.
++ Simulot

**Comment by rockandska** [comment]
> Subtitles are send in its own stream in DASH stream, and are not forced on the video stream. Alas FFMEG can't handle the stream. Depending on the version, FFMPEG just ignores it otherwise stops before downloading anything.
> 
> I have tested with ffmpeg v3.4 coming with ubuntu and the latest available 4.2.

I'm not sure if it is the case for all providers, but at least for artetv, the video have the subtitles hard-coded and are available directly in the mp4 from the test I just done.

https://api.arte.tv/api/player/v1/config/fr/091111-001-A?autostart=1&lifeCycle=1

Slow quality - original version with subtitles:
```
$ wget https://arteptweb-a.akamaihd.net/am/ptweb/091000/091100/091111-001-A_MQ_0_VO-STF_04849640_MP4-300_AMM-PTWEB_1IychKvGPo.mp4
$ vlc 091111-001-A_MQ_0_VO-STF_04849640_MP4-300_AMM-PTWEB_1IychKvGPo.mp4
```

> 
> More problematic, the audio stream labelled "VO" is in French even for English shows like Brokenwood. English isn't available on webplayer too.
> ++ Simulot

Maybe for this show and francetv provider, but not for artetv.
And if VO is french for some shows, we could assume that the VO is not available and is not something that aspiratv could deal with since it is not available on the provider itself.

Regards,

**Comment by simulot** [comment]
My comments was on FRANCETV. 
Yes, ARTETV exposes several audio tracks and subtitle. I'll add command line options and configuration parameter.

**Comment by simulot** [comment]
This issue is now fixed for FranceTV
