### ISSUE TITLE
tilde does not expand

### ISSUE THREAD

**Issue by rockandska** [simulot/aspiratv#45]
Hi,

`~/` is not expanded to $HOME with 0.9.0 and previous

```
$ aspiratv --provider="artetv" --destination="~/Videos" download "united we stream"
```

A literally `~` directory is created where you lunch aspiratv

Regards,

**Comment by simulot** [comment]
From ask ubuntu: [here](https://askubuntu.com/questions/890415/why-couldnt-i-use-instead-of-home-username-when-giving-the-file-pat) :
You need to understand that ~ is normally expanded by the shell; the programs you call never see it, they see the full pathname as inserted by bash. But this only happens when the tilde is at the start of an argument (and is not quoted). -
 
Hopefully, the program accept also a command line like :
`$ aspiratv --provider artetv --destination ~/Videos download "united we stream"`

In this case, when the shell handles the ~/Videos, it detects this is a file name, and does its job. Then the program gets the full path.

**Comment by rockandska** [comment]
I am well aware that it is the shell who generally make the expand of `~`.
Despite that, it is not uncommon to see many scripts to expand path receive from command line or config files to avoid any problems.

For example, if you use `~` with the json configuration it will not be expanded since it will not be expanded by the shell.

Anyway, it is not the most important.

**Comment by simulot** [comment]
Indeed. 
The program is intended to run on Windows also, and I prefer avoiding OS dependent code as much as possible.
 
However, you can use environment variables in json config file or on the command line, thanks to golang's standard library.

Here is my config.json:
``` json
  "Destinations": {
    "Séries": "${HOME}/Videos/DL/Séries",
    "Documentaires": "${HOME}/Videos/DL/Documentaires",
    "Jeunesse": "${HOME}/Videos/DL/Jeunesse",
    "News": "${HOME}/Videos/DL/News"
  }
```
