### ISSUE TITLE
Show Mismatch when part of the name is common

### ISSUE THREAD

**Issue by evoblicec** [simulot/aspiratv#55]
Hi, thanks for this software, amazing job!

I'm having an issue with a particular show `La maison France 5` with FranceTv Provider

There is currently two shows sharing that name 

1. `La maison France 5`
2. `La maison France 5, émission spéciale Perene`

When searching for  `La maison France 5` the result is the number `2`, it should be number `1` as it is an exact match

Let me know if I can help for the troubleshooting.

**Comment by simulot** [comment]
Hi, thank you.
Sorry for the late answer.
The show name is passed to France TV search engine. On the returned list, only shows containing the show name are kept. (case insensitive search).  In your case, to 2 shows are matching. 

I would like to keep the possibility to search using partial title. This is easy and work most of the time.

So we need a way to indicate we want an exact  instead of partial match
I see 2 options:
1. Add a flag to command line and config file like --exact=true
1. Using a special char in the show title like ">La maison France 5"

I prefer the 1st, and you?

Don't forget that the system is totally dependant on the way the show tittle are encoded by the broadcaster. For "La Maison France 5" I have got:
- La maison France 5
- La Maison France 5, émission spéciale Perene
- La maison France 5, spéciale Perene
- La Maison France 5, spéciale Perene

Note maison/Maison ...

**Comment by evoblicec** [comment]
Hi thank you for your answer!

I already implemented a quick dirty fix myself similar to 1. so it covers the use case.

I can see a 3rd possibility, introducing regex and using a matching pattern instead of a string.
It covers more uses cases and it is more évolutive.

What to do you think?

**Comment by simulot** [comment]
I'm not favorable to regexp:

1. Having a plain text is required to query the web site. This plain text can't derivate form regexp. Therefore we would need the plain text **and** the regexp.
1. REGEXP isn't for real humans (I mean my children, my parents...). Maybe you have good use cases?

Yes, the search is already case insensitive. The problem come from linux file system which isn't. As the show name is also the directory name, a new directory is created for each new variant.
I see 2 options:
1. Try to reuse the existing path whatever the case of the new show. This works like that on Windows, but I have to implement it on linux.
1. Add a parameter to force the show's directory at a given value either on command line or config file.

**Comment by evoblicec** [comment]
I wasn't pushing for regexp in place of title search.

You could add a regexp attribute.
Title will still be used for searching but when regexp is present it will be used for matching results instead of the title itself.

Minimum code changes and no regressions that way. 

For the folder part I don't see any issues with case. 
I already configured a different folder for each task anyway.
By the way adding an option to not create the subfolder structure could be useful

**Comment by simulot** [comment]
Sounds good.

I'm going to implement following:
- optional  path for a show. So any episode will be stored in the given path, despite inconsistent naming by the provider
- optional name filter with regexp

**Comment by evoblicec** [comment]
Thanks! Looking forward to test the changes!

**Comment by simulot** [comment]
Options --title-filter and --title-exclude are now added to master branch.

**Comment by evoblicec** [comment]
> Options --title-filter and --title-exclude are now added to master branch.

Perfect, tested and it is working as intended. I am able to filter matched video based on regex.
May I suggest adding a link to [https://regex101.com](url) in the Readme, it's a great help building regex.

Looking to the option to download files at the root of destination folder without subfolder structure.

Thank you for the changes!
